# Generated by Django 4.2.30 on 2026-06-07 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='My Portfolio Profile', max_length=100)),
                ('bio', models.TextField(blank=True, default='Welcome to my custom profile! You can edit this bio in your dashboard.')),
                ('location', models.CharField(blank=True, default='Earth', max_length=100)),
                ('template_choice', models.CharField(choices=[('material', 'Material Theme'), ('dark_cyber', 'Cyberpunk Glow'), ('glassmorphism', 'Glassmorphism'), ('minimalist', 'Minimalist Clean')], default='material', max_length=20)),
                ('primary_color', models.CharField(default='#3f51b5', max_length=7)),
                ('accent_color', models.CharField(default='#ff4081', max_length=7)),
                ('font_family', models.CharField(choices=[('Roboto', 'Roboto (Clean/Modern)'), ('Inter', 'Inter (Sleek/Tech)'), ('Playfair Display', 'Playfair Display (Elegant/Serif)'), ('Fira Code', 'Fira Code (Developer/Monospace)')], default='Roboto', max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('github_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('website_url', models.URLField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.profile')),
            ],
        ),
    ]
